### ISSUE TITLE
Mind releasing a new version to the registry?

### ISSUE THREAD

**Issue by dcgrigsby** [lukemerrick/IEXTools.jl#10]
Hi, Luke -

Thanks for this package.  Would you mind releasing an updated version to the registry?

I'm using Pluto, and its new package management system can automatically manage packages that are in the package registry.  This makes it easier to share notebooks as, for each notebook, Pluto can install the necessary packages automatically.  I can turn off the package management and use the github version (I'm interested in DEEP not TOPS) but it'd be nice to be able to use the package management.

Thanks,

Dan

**Comment by lukemerrick** [comment]
If you're using the package, I'll just go ahead and add you as a collaborator so you can also apply any bugfixes my definitely-not-perfect code may need, too. ^_^

**Comment by lukemerrick** [comment]
A version 1.2 should be hitting the registry soon now: https://github.com/lukemerrick/InvestorsExchange.jl/commit/a130fd5b88aa994b45ddd9acd0946bc4c80106b9#commitcomment-54901074

**Comment by dcgrigsby** [comment]
Luke:  Thanks!  That's appreciated, on both counts.  I'm early stages of creating a Pluto notebook that will play back the [ladder](https://www.google.com/search?q=bid+ask+ladder&client=firefox-b-1-d&sxsrf=AOaemvKNc6ZPWxHZBjq7zhKMADClx_H5ow:1628967599063&source=lnms&tbm=isch&sa=X&ved=2ahUKEwiEsd6YmbHyAhWMQs0KHXVUAV8Q_AUoAXoECAEQAw&biw=1280&bih=595#imgrc=SSyCdxNt2aQAkM) for a given ticker symbol.  I'll dig in and see what I find and share the notebook if/when I get it to a usable point.

**Comment by lukemerrick** [comment]
Sounds like a plan! Since I only implemented parsing of TradeReportMessage-type messages in the TOPS/DEEP feeds, you'll probably need to extend the library a little bit to handle parsing other message types that capture the order book. The [PDF for the DEEP specification can be found on the IEX website](https://iextrading.com/docs/IEX%20DEEP%20Specification.pdf).

**Comment by lukemerrick** [comment]
I think the actual struct types are defined for some of the message types you're looking to parse, but right now the PCAP file iterator just skips message types other than TradeReportMessage: https://github.com/lukemerrick/InvestorsExchange.jl/blob/master/src/read_pcap.jl#L117

**Comment by dcgrigsby** [comment]
I'll plan on adding them.  I'll do a fork to segregate my work and issue a PR just so you can have eyes on it, if you want.
